title: Chang Huang's Homepage
page-top-title: Chang Huang
top-section-bg-text: Computer Science
home-subtitle: Chang Huang&ensp;|&ensp;黄畅
copyright-text: '&copy; Chang Huang 2026. All Rights Reserved.'
